/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as UsersEditUserIdRouteImport } from './routes/users/edit/$userId'
import { Route as UsersUserAddIndexRouteImport } from './routes/users/user/add/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersEditUserIdRoute = UsersEditUserIdRouteImport.update({
  id: '/users/edit/$userId',
  path: '/users/edit/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserAddIndexRoute = UsersUserAddIndexRouteImport.update({
  id: '/users/user/add/',
  path: '/users/user/add/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/users': typeof UsersIndexRoute
  '/users/edit/$userId': typeof UsersEditUserIdRoute
  '/users/user/add': typeof UsersUserAddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/users': typeof UsersIndexRoute
  '/users/edit/$userId': typeof UsersEditUserIdRoute
  '/users/user/add': typeof UsersUserAddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/users/': typeof UsersIndexRoute
  '/users/edit/$userId': typeof UsersEditUserIdRoute
  '/users/user/add/': typeof UsersUserAddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/users' | '/users/edit/$userId' | '/users/user/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/users' | '/users/edit/$userId' | '/users/user/add'
  id: '__root__' | '/' | '/users/' | '/users/edit/$userId' | '/users/user/add/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersEditUserIdRoute: typeof UsersEditUserIdRoute
  UsersUserAddIndexRoute: typeof UsersUserAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/edit/$userId': {
      id: '/users/edit/$userId'
      path: '/users/edit/$userId'
      fullPath: '/users/edit/$userId'
      preLoaderRoute: typeof UsersEditUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/user/add/': {
      id: '/users/user/add/'
      path: '/users/user/add'
      fullPath: '/users/user/add'
      preLoaderRoute: typeof UsersUserAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersEditUserIdRoute: UsersEditUserIdRoute,
  UsersUserAddIndexRoute: UsersUserAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
