/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignatureServiceRouteImport } from './routes/signature-service'
import { Route as SignEdoRouteImport } from './routes/sign-edo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManagerStatsRouteImport } from './routes/manager/stats'
import { Route as ManagerLogsRouteImport } from './routes/manager/logs'
import { Route as ManagerDocumentsRouteImport } from './routes/manager/documents'
import { Route as ManagerAddRouteImport } from './routes/manager/add'
import { Route as ManagerUsersIndexRouteImport } from './routes/manager/users/index'
import { Route as ManagerUsersAddRouteImport } from './routes/manager/users/add'

const SignatureServiceRoute = SignatureServiceRouteImport.update({
  id: '/signature-service',
  path: '/signature-service',
  getParentRoute: () => rootRouteImport,
} as any)
const SignEdoRoute = SignEdoRouteImport.update({
  id: '/sign-edo',
  path: '/sign-edo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerStatsRoute = ManagerStatsRouteImport.update({
  id: '/manager/stats',
  path: '/manager/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerLogsRoute = ManagerLogsRouteImport.update({
  id: '/manager/logs',
  path: '/manager/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDocumentsRoute = ManagerDocumentsRouteImport.update({
  id: '/manager/documents',
  path: '/manager/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerAddRoute = ManagerAddRouteImport.update({
  id: '/manager/add',
  path: '/manager/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersIndexRoute = ManagerUsersIndexRouteImport.update({
  id: '/manager/users/',
  path: '/manager/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerUsersAddRoute = ManagerUsersAddRouteImport.update({
  id: '/manager/users/add',
  path: '/manager/users/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-edo': typeof SignEdoRoute
  '/signature-service': typeof SignatureServiceRoute
  '/manager/add': typeof ManagerAddRoute
  '/manager/documents': typeof ManagerDocumentsRoute
  '/manager/logs': typeof ManagerLogsRoute
  '/manager/stats': typeof ManagerStatsRoute
  '/manager/users/add': typeof ManagerUsersAddRoute
  '/manager/users': typeof ManagerUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-edo': typeof SignEdoRoute
  '/signature-service': typeof SignatureServiceRoute
  '/manager/add': typeof ManagerAddRoute
  '/manager/documents': typeof ManagerDocumentsRoute
  '/manager/logs': typeof ManagerLogsRoute
  '/manager/stats': typeof ManagerStatsRoute
  '/manager/users/add': typeof ManagerUsersAddRoute
  '/manager/users': typeof ManagerUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-edo': typeof SignEdoRoute
  '/signature-service': typeof SignatureServiceRoute
  '/manager/add': typeof ManagerAddRoute
  '/manager/documents': typeof ManagerDocumentsRoute
  '/manager/logs': typeof ManagerLogsRoute
  '/manager/stats': typeof ManagerStatsRoute
  '/manager/users/add': typeof ManagerUsersAddRoute
  '/manager/users/': typeof ManagerUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-edo'
    | '/signature-service'
    | '/manager/add'
    | '/manager/documents'
    | '/manager/logs'
    | '/manager/stats'
    | '/manager/users/add'
    | '/manager/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-edo'
    | '/signature-service'
    | '/manager/add'
    | '/manager/documents'
    | '/manager/logs'
    | '/manager/stats'
    | '/manager/users/add'
    | '/manager/users'
  id:
    | '__root__'
    | '/'
    | '/sign-edo'
    | '/signature-service'
    | '/manager/add'
    | '/manager/documents'
    | '/manager/logs'
    | '/manager/stats'
    | '/manager/users/add'
    | '/manager/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignEdoRoute: typeof SignEdoRoute
  SignatureServiceRoute: typeof SignatureServiceRoute
  ManagerAddRoute: typeof ManagerAddRoute
  ManagerDocumentsRoute: typeof ManagerDocumentsRoute
  ManagerLogsRoute: typeof ManagerLogsRoute
  ManagerStatsRoute: typeof ManagerStatsRoute
  ManagerUsersAddRoute: typeof ManagerUsersAddRoute
  ManagerUsersIndexRoute: typeof ManagerUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signature-service': {
      id: '/signature-service'
      path: '/signature-service'
      fullPath: '/signature-service'
      preLoaderRoute: typeof SignatureServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-edo': {
      id: '/sign-edo'
      path: '/sign-edo'
      fullPath: '/sign-edo'
      preLoaderRoute: typeof SignEdoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/stats': {
      id: '/manager/stats'
      path: '/manager/stats'
      fullPath: '/manager/stats'
      preLoaderRoute: typeof ManagerStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/logs': {
      id: '/manager/logs'
      path: '/manager/logs'
      fullPath: '/manager/logs'
      preLoaderRoute: typeof ManagerLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/documents': {
      id: '/manager/documents'
      path: '/manager/documents'
      fullPath: '/manager/documents'
      preLoaderRoute: typeof ManagerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/add': {
      id: '/manager/add'
      path: '/manager/add'
      fullPath: '/manager/add'
      preLoaderRoute: typeof ManagerAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/': {
      id: '/manager/users/'
      path: '/manager/users'
      fullPath: '/manager/users'
      preLoaderRoute: typeof ManagerUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/users/add': {
      id: '/manager/users/add'
      path: '/manager/users/add'
      fullPath: '/manager/users/add'
      preLoaderRoute: typeof ManagerUsersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignEdoRoute: SignEdoRoute,
  SignatureServiceRoute: SignatureServiceRoute,
  ManagerAddRoute: ManagerAddRoute,
  ManagerDocumentsRoute: ManagerDocumentsRoute,
  ManagerLogsRoute: ManagerLogsRoute,
  ManagerStatsRoute: ManagerStatsRoute,
  ManagerUsersAddRoute: ManagerUsersAddRoute,
  ManagerUsersIndexRoute: ManagerUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
